version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb_container
    ports:
      - "${MONGO_PORT:-10000}:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD} 
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local